apiVersion: v1
kind: Pod
metadata:
  name: my-pod-volume
  namespace: example
spec:
  containers:
  - name: main
    image: busybox:latest
    ports:
    - containerPort: 80
    command: ['sh', '-c', 'echo Chihuahua > /home/dog.txt']
    volumeMounts:
    - mountPath: /home
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /mnt/dog
      type: DirectoryOrCreate
  restartPolicy: Never
