apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: example
spec:
  selector:
    app: static-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
