apiVersion: v1
kind: Pod
metadata:
  name: my-multi-container-pod
  namespace: example
spec:
  containers:
  - name: main
    image: nginx:latest
    ports:
    - name: web
      protocol: TCP
      containerPort: 80
  - name: helper
    image: busybox:latest
    command: ['sh', '-c', 'sleep infinity']
